repos:
-   repo: local
    hooks:
    - id: generate-auto-readme
      name: Generar Automaticamente README.md
      entry: ./gen_readme.sh
      language: script
      types: [text]
-   repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
